syntax on

set number
set cursorline
" set cursorlineopt=number
set nobackup
set history=100
set clipboard+=unnamed
set bufhidden=hide
setlocal noswapfile
set ruler
set rulerformat=%20(%2*%<%f%=\ %m%r\ %3l\ %c\ %p%%%)
set mouse=a
set showmatch
set backspace=indent,eol,start
" set hlsearch
set incsearch
set autochdir
set wrap
set nowrapscan
set noeb
set nocompatible
set laststatus=2
set statusline=%F%r\ [%l,%v,%P]\ [HEX=%B]
set wildmenu
set showcmd
set expandtab
set tabstop=4
set shiftwidth=4


" ===============
"  filetype
" ===============
autocmd BufNewFile,BufRead *.html,*.htm,*.css,*.js
            \ set noexpandtab |
            \ set tabstop=2 |
            \ set shiftwidth=2
" set to  markdown
autocmd BufNewFile,BufRead *.md
            \ set fileformat=unix |
            \ map <F7> :! code % <cr><cr> |
            \ imap <C-b> <br/> |
            \ set nofoldenable


" set for TagList
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
set tags=$PWD/tags   " set tags to current folder.

let g:vim_markdown_frontmatter=1



" ==============================
" install vundle for vim "
" =============================
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim    " Vundle 安装目录
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'tomtom/tlib-vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
call vundle#end()
filetype plugin indent on

"== vim-markdown =="
let g:vim_markdown_fenced_languages = ['csharp=cs']
let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1


" == kite-python == "
let g:kite_auto_complete=1
let g:kite_tab_complete=1
set completeopt+=menuone
" set completeopt+=oninsert
set completeopt+=longest
set completeopt+=preview
autocmd completeDone * if !pumvisible() | pclose | endif
set belloff+=ctrlg   " if vim beeps during completion.

" Plugin 'jiazhoulvke/MarkdownView'"
" nmap mdv :MarkdownView"
" Plugin 'godlygeek/tabular'""
" Plugin 'plasticboy/vim-markdown'""
" Plugin 'iamcco/markdown-preview.vim'"
" nmap <silent> <F7> <Plug>MarkdownPreview"        " 普通模式"
" imap <silent> <F7> <Plug>MarkdownPreview"        " 插入模式"
" nmap <silent> <F8> <Plug>StopMarkdownPreview"    " 普通模式"
" imap <silent> <F8> <Plug>StopMarkdownPreview"    " 插入模式"


" ======================================
" normal mode key maps.
" ======================================
nmap tl :Tlist<cr>
nmap hl :set hlsearch<cr>
nmap nls :set nohlsearch<cr>
nmap q1 :q!<cr>
nmap ww :w<cr>
nmap wq :wq<cr>
nmap ii :
nmap ir :! 
nmap cc :! 
nmap vp :vsplit<cr>
nmap sp :split<cr>
nmap wp :set wrap<cr>
nmap nwp :set nowrap<cr>
nmap ntab :set noexpandtab
nmap etab :set expandtab
nmap vvim :vsp ~/.vimrc<cr>
nmap svim :so ~/.vimrc<cr>
nmap <C-i> :
nmap cln  :set cursorline cursorlineopt=number
nmap ncln :set nocursorlineo
nmap nfd :set nofoldenable
nmap efd  :set foldenable
" map to run PluginInstall.
nmap pin :PluginInstall<cr>

" ===============================
" Insert mode key maps
" ================================
