set number
set cursorline
set nobackup
set history=100
set clipboard+=unnamed
syntax on
setlocal noswapfile
set bufhidden=hide
set ruler
set rulerformat=%20(%2*%<%f%=\ %m%r\ %3l\ %c\ %p%%%)
set mouse=a
set showmatch
set backspace=indent,eol,start
" set hlsearch
set autochdir
set wrap

nmap sls :set hlsearch<cr>
nmap snls :set nohlsearch<cr>
nmap ww :w<cr>
nmap wq :wq<cr>
nmap ii :
nmap vp :vsplit<cr>
nmap sp :split<cr>
nmap swp :set wrap<cr>
nmap snwp :set nowrap<cr>
nmap sntab :set noexpandtab
nmap stab :set expandtab
nmap vvim :vsp ~/.vimrc<cr>
" insert -> nornal
imap <C-j> <Esc>
nmap <C-i> :

autocmd BufNewFile,BufRead *.html,*.htm,*.css,*.js set noexpandtab tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.py,*.sh set expandtab tabstop=4 shiftwidth=4

let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
nmap tl :Tlist<cr>
set tags=$PWD/tags

let g:vim_markdown_frontmatter=1

" install vundle for vim "
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim    " Vundle 安装目录
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'tomtom/tlib-vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
call vundle#end()
filetype plugin indent on

"== vim-markdown =="
let g:vim_markdown_fenced_languages = ['csharp=cs']
let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1

set foldenable
nmap snfd :set nofoldenable
nmap sfd  :set foldenable

" Plugin 'jiazhoulvke/MarkdownView'"
" nmap mdv :MarkdownView"
" Plugin 'godlygeek/tabular'""
" Plugin 'plasticboy/vim-markdown'""
" Plugin 'iamcco/markdown-preview.vim'"
" nmap <silent> <F7> <Plug>MarkdownPreview"        " 普通模式"
" imap <silent> <F7> <Plug>MarkdownPreview"        " 插入模式"
" nmap <silent> <F8> <Plug>StopMarkdownPreview"    " 普通模式"
" imap <silent> <F8> <Plug>StopMarkdownPreview"    " 插入模式"
" map to run PluginInstall "

" map to run PluginInstall.
nmap plgin :PluginInstall<cr>
" map to edit .vimrc"
nmap svim :so ~/.vimrc<cr>
" nmap for markdown preview."
nmap rmdv :! remarkable %<cr><cr>
nmap typv :! typora %<cr><cr>
nmap vmd :! vnote %<cr><cr>
nmap <F7> :! vnote %<cr><cr>

" map to insert <br/> .
imap <C-b>  <br/> 
