
export DWN=~/Downloads
export DOC=~/Documents
export WS=~/workspace
export MYGIT=~/.mygit
export IBUS=$MYGIT/IBus
export MYPY=$MYGIT/mypy
export MYSH=$MYGIT/mysh

# alias for apt
alias aud='sudo apt-get update -y'
alias agd='sudo apt-get upgrade -y'
alias arm='sudo apt-get autoremve -y'
alias aiy='sudo apt-get install -y'

# alias for sys
alias sbc='source ~/.bashrc'
alias vbc='vim ~/.bashrc'
alias vba='vim ~/.bash_aliases'
alias vvim='vim ~/.vimrc'
alias vbe="vim ~/.bash_exports"

# alias for path
alias cdb="cd -"
alias cdu="cd .."
alias cdl="cd $DWN"
alias cdc="cd $DOC"
alias cws="cd $WS"
alias cgit="cd $MYGIT"
alias cpy="cd $MYPY"
alias csh="cd $MYSH"
alias cbin="cd $HBIN"
alias cbpy="cd $HBIN/py"
alias cbsh="cd $HBIN/sh"
alias cmd="cd $MYGIT/markdown"
alias cwn="cd $MYGIT/worknotes"
alias cis="cd $MYGIT/ibus"
alias cmn="cd $MYGIT/mynotes"
alias ctn="cd $MYGIT/technotes"
alias cles="cd $MYGIT/linux-env-setup"
alias ces="cd $MYGIT/essentials"

# alias for git
alias gst="git status"
alias gss='git status -s'
alias gdf="git diff"
alias gdt='git difftool'
alias gaa="git add"
alias gbr="git branch"
alias gbra="git branch -a"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gfp="git format-patch"
alias gfph="git format-patch HEAD~"
alias glg="git log"
alias glgs="git log --stat"
alias glgn="git log --name-status"
alias glga="git log --pretty=oneline --graph --decorate --all"
alias gsw="git show"
alias gsp='git show -p'
alias gpm='git push origin master'
alias grh='git reset --hard'
alias grhh='git reset --hard HEAD~'


# alias for python
mygit="$MYGIT/mysh/git/mygit.sh"
alias mygitp="bash $mygit -p"
alias mygitm="bash $mygit -m"
alias mygitn="bash $mygit -n"
alias mygitc="bash $mygit -n -m"

# alias mdc="python3 $HBIN/py/mdcrypto.pyc"
alias mde="python3 $HBIN/py/mdcrypto.pyc -e"
alias mdd="python3 $HBIN/py/mdcrypto.pyc -d"

alias bwn="python3 $MYPY/tools/baiduyun/bakmarkdown/bakworknotes.py -u"
alias bmn="python3 $MYPY/tools/baiduyun/bakmarkdown/bakmynotes.py -u"

#alias for shell
alias docker_ubuntu="sudo docker run -it ubuntu /bin/bash"

# alias for ibus
alias ibh="python3 $MYPY/linux/ibus/ibus.py -h"
alias iba="python3 $MYPY/linux/ibus/ibus.py -a"
alias ibu="python3 $MYPY/linux/ibus/ibus.py -u"
alias ibr="python3 $MYPY/linux/ibus/ibus.py -r"
alias ibs="python3 $MYPY/linux/ibus/ibus.py -s"

# alias for others
# alias cpyc="find . -name __pycache__ | xargs rm -rf && find . -name *.pyc | xargs rm -rf"
alias cpyc="find . -name __pycache__ -o -name *.pyc | xargs -I {} rm -rf {}"


# alias for ctags
alias ctags='ctags -R'

# alias for linux
alias getpass='openssl rand -base64 '
alias untar='tar -zxvf '
alias rmd='remarkable '
alias tya='typora '
alias hap='haroopad '
alias bdy="baiduyun.py "
