
export WS=~/workspace
export GIT=~/.mygit
export IBUS=$GIT/IBus
export MYPY=$GIT/mypy
export MYSH=$GIT/mysh
# alias for apt
alias aud='sudo apt-get update -y'
alias agd='sudo apt-get upgrade -y'
alias arm='sudo apt-get autoremve -y'
alias aiy='sudo apt-get install -y'

# alias for sys
alias sbc='source ~/.bashrc'
alias vbc='vim ~/.bashrc'
alias vba='vim ~/.bash_aliases'

# alias for path
alias cdb="cd -"
alias cdu="cd .."
alias cdl="cd ~/Downloads"
alias cdc="cd ~/Documents"
alias cws="cd $WS"
alias cgit="cd $GIT"
alias cpy="cd $MYPY"
alias csh="cd $MYSH"
alias cbin="cd $HBIN"
alias cbpy="cd $HBIN/py"
alias cbsh="cd $HBIN/sh"
alias cmd="cd $GIT/markdown"
alias cwn="cd $GIT/worknotes"
alias cis="cd $GIT/ibus"
alias cmn="cd $GIT/mynotes"
alias ctn="cd $GIT/technotes"
alias clx='cd $GIT/linux-env-setup'

# alias for git
alias gst="git status"
alias gss='git status -s'
alias gdf="git diff"
alias gdt='git difftool'
alias gaa="git add"
alias gbr="git branch"
alias gbra="git branch -a"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gfp="git format-patch"
alias gfph="git format-patch HEAD~"
alias glg="git log"
alias glga="git log --pretty=oneline --graph --decorate --all"
alias gsw="git show"
alias gsp='git show -p'
alias gpm='git push origin master'
alias grh='git reset --hard'
alias grhh='git reset --hard HEAD~'


# alias for python
alias mygit="bash $GIT/mysh/git/mygit.sh"
alias mygitp="bash $GIT/mysh/git/mygit.sh -p"
alias mygitm="bash $GIT/mysh/git/mygit.sh -m"
alias mygitn="bash $GIT/mysh/git/mygit.sh -n"
alias mygits="bash $GIT/mysh/git/mygit.sh -n -m"

#alias mdc="python3 $HBIN/py/mdcrypto.pyc"
alias mde="python3 $HBIN/py/mdcrypto.pyc -e"
alias mdd="python3 $HBIN/py/mdcrypto.pyc -d"


#alias for shell
alias docker_ubuntu="sudo docker run -it ubuntu /bin/bash"

# alias for ibus
alias iba="python3 $MYPY/linux/ibus/ibus.py -a"
alias ibu="python3 $MYPY/linux/ibus/ibus.py -u"
alias ibr="python3 $MYPY/linux/ibus/ibus.py -r"
alias ibs="python3 $MYPY/linux/ibus/ibus.py -s"

# alias for others
alias cpyc="find . -name __pycache__ | xargs rm -rf && find . -name *.pyc | xargs rm -rf"

# alias for ctags
alias ctags='ctags -R'

# alias for linux
alias getpass='openssl rand -base64 '
alias untar='tar -zxvf '
alias rmd='remarkable '
alias tya='typora '
alias hap='haroopad '
